### ISSUE TITLE
TypeError: Function.prototype.toString is not generic

### ISSUE THREAD

**Issue by besuikerd** [hermanbanken/RxFiddle#2]
The following code gives an error

```
function id(x){return x;}


var o1 = Rx.Observable.just(2,3,4)
  .expand(x => Rx.Observable.ofWithScheduler(Rx.Scheduler.async, x * x))
  .take(10)
  .map(id)
  .filter(x => true)
  .map(id)
  .map(id)
  .map(id)
  .map(id)
  .map(id)
  .map(id)
  
var o2 = Rx.Observable.just(1)
  .map(id)
  

o1.merge(o2).subscribe()
```

**Comment by hermanbanken** [comment]
Solved with 5cee62ef2186236f2eb42d319f981da0188b61dd. And apparently the just method has as second argument a scheduler, so alternatively you could write:

```javascript
function id(x){return x;}
var o1 = Rx.Observable.ofWithScheduler(Rx.Scheduler.async, 2,3,4)
  .expand(x => Rx.Observable.just(x * x, Rx.Scheduler.async))
  .take(10)
  .map(id)
  .filter(x => true)
  .map(id)
  .map(id)
  .map(id)
  .map(id)
  .map(id)
  .map(id)
var o2 = Rx.Observable.just(1)
  .map(id)
o1.merge(o2).subscribe()
```

[RxFiddle link](rxfiddle.net#code=ZnVuY3Rpb24gaWQoeCl7cmV0dXJuIHg7fQoKCnZhciBvMSA9IFJ4Lk9ic2VydmFibGUub2ZXaXRoU2NoZWR1bGVyKFJ4LlNjaGVkdWxlci5hc3luYywgMiwzLDQpCiAgLmV4cGFuZCh4ID0+IFJ4Lk9ic2VydmFibGUuanVzdCh4ICogeCwgUnguU2NoZWR1bGVyLmFzeW5jKSkKICAudGFrZSgxMCkKICAubWFwKGlkKQogIC5maWx0ZXIoeCA9PiB0cnVlKQogIC5tYXAoaWQpCiAgLm1hcChpZCkKICAubWFwKGlkKQogIC5tYXAoaWQpCiAgLm1hcChpZCkKICAubWFwKGlkKQogIAp2YXIgbzIgPSBSeC5PYnNlcnZhYmxlLmp1c3QoMSkKICAubWFwKGlkKQogIAoKbzEubWVyZ2UobzIpLnN1YnNjcmliZSgp&type=editor)
